CREATE TABLE [dbo].[SELLER_TABLE]
(
	[SELLER_ID] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [SELLER_NAME] NVARCHAR(50) NOT NULL, 
    [SELLER_SHOP_NAME] NVARCHAR(50) NOT NULL, 
    [SELLER_EMAIL] NVARCHAR(50) NOT NULL, 
    [SELLER_SHOP_ADDRESS] NVARCHAR(MAX) NOT NULL, 
    [GENDER] NVARCHAR(50) NOT NULL, 
    [SELLER_PHONE_NO] NUMERIC NOT NULL, 
    [TRADE_LICENSE] NVARCHAR(50) NOT NULL, 
    [SELLER_PASSWORD] NVARCHAR(50) NOT NULL
)
